# Use the official Python Alpine image
FROM python:3.11-alpine

# Set the working directory inside the container
WORKDIR /myapp

# Copy hello.py into the container
COPY hello.py .

# Command to run the Python script
CMD ["python", "hello.py"]